CREATE TABLE IF NOT EXISTS "statistics" (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    total INT NOT NULL,
    icon VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);